// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // migrate/introspect precisam de conexão direta — a pooler do Neon
    // (usada em runtime via DATABASE_URL) não suporta os advisory locks
    // que o Prisma Migrate usa.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
